### ISSUE TITLE
Improve Error Handling

### ISSUE THREAD

**Issue by JosiahBull** [JosiahBull/dds#2]
# Issue or Bug

## Description

The application should gracefully handle errors, recovering or displaying them to the user for action where appropriate. Right now we throw a hard panic every time and just use `human_panic` to make it pretty.

## Tasks/General Thoughts

- [ ] Flesh out error.rs
- [ ] Remove use of unwraps
- [ ] Add lints to deny unwrap in future
