### ISSUE TITLE
Replace useless ETA

### ISSUE THREAD

**Issue by JosiahBull** [JosiahBull/dds#3]
# Issue or Bug

## Description

The ETA is really terrible, and bounces all over the place. A more useful measure would be number of blocks/second read over the last 10 seconds.

## Tasks/General Thoughts

- [ ] Remove existing eta implementation
- [ ] Implement rolling average of blocks/sec
- [ ] Implement for both single and multithreaded
